apiVersion: v1
kind: Service
metadata:
  name: student-frontend
  labels:
    app.kubernetes.io/name: student-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: student-management
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: student-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
