apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-frontend
  labels:
    app.kubernetes.io/name: student-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: student-management
automountServiceAccountToken: false
